import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageSettings {
  static final LanguageSettings instance = LanguageSettings._();
  LanguageSettings._();

  final ValueNotifier<String> locale = ValueNotifier('es');

  Future<void> init() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final saved = prefs.getString('app_locale');
      if (saved != null && ['es', 'en'].contains(saved)) {
        locale.value = saved;
      }
    } catch (_) {}
  }

  Future<void> setLocale(String lang) async {
    locale.value = lang;
    try {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString('app_locale', lang);
    } catch (_) {}
  }

  String tr(String key) {
    final map = _translations[locale.value] ?? _translations['es']!;
    return map[key] ?? _translations['es']![key] ?? key;
  }

  /// Translates a service name stored in Spanish in the database
  String trService(String spanishName) {
    if (locale.value == 'en') {
      return _serviceTranslations[spanishName] ?? spanishName;
    }
    return spanishName;
  }

  /// Translates a country name stored in Spanish in the database
  String trCountry(String spanishName) {
    if (locale.value == 'en') {
      return _countryTranslations[spanishName] ?? spanishName;
    }
    return spanishName;
  }

  /// Translates a city name stored in Spanish in the database
  String trCity(String spanishName) {
    if (locale.value == 'en') {
      return _cityTranslations[spanishName] ?? spanishName;
    }
    return spanishName;
  }

  static const Map<String, String> _countryTranslations = {
    'España': 'Spain',
    'Francia': 'France',
    'Italia': 'Italy',
    'Alemania': 'Germany',
    'Reino Unido': 'United Kingdom',
    'Gran Bretaña': 'Great Britain',
    'Inglaterra': 'England',
    'Portugal': 'Portugal',
    'Estados Unidos': 'United States',
    'México': 'Mexico',
    'Argentina': 'Argentina',
    'Brasil': 'Brazil',
    'Colombia': 'Colombia',
    'Chile': 'Chile',
    'Perú': 'Peru',
    'Venezuela': 'Venezuela',
    'Ecuador': 'Ecuador',
    'Bolivia': 'Bolivia',
    'Uruguay': 'Uruguay',
    'Paraguay': 'Paraguay',
    'Japón': 'Japan',
    'China': 'China',
    'Australia': 'Australia',
    'Nueva Zelanda': 'New Zealand',
    'Canadá': 'Canada',
    'Holanda': 'Netherlands',
    'Países Bajos': 'Netherlands',
    'Bélgica': 'Belgium',
    'Suiza': 'Switzerland',
    'Austria': 'Austria',
    'Grecia': 'Greece',
    'Turquía': 'Turkey',
    'Rusia': 'Russia',
    'Polonia': 'Poland',
    'República Checa': 'Czech Republic',
    'Hungría': 'Hungary',
    'Croacia': 'Croatia',
    'Eslovenia': 'Slovenia',
    'Serbia': 'Serbia',
    'Rumanía': 'Romania',
    'Bulgaria': 'Bulgaria',
    'Noruega': 'Norway',
    'Suecia': 'Sweden',
    'Dinamarca': 'Denmark',
    'Finlandia': 'Finland',
    'Irlanda': 'Ireland',
    'Escocia': 'Scotland',
    'Gales': 'Wales',
    'India': 'India',
    'Tailandia': 'Thailand',
    'Vietnam': 'Vietnam',
    'Indonesia': 'Indonesia',
    'Singapur': 'Singapore',
    'Malasia': 'Malaysia',
    'Filipinas': 'Philippines',
    'Corea del Sur': 'South Korea',
    'Corea del Norte': 'North Korea',
    'Emiratos Árabes Unidos': 'United Arab Emirates',
    'Arabia Saudí': 'Saudi Arabia',
    'Catar': 'Qatar',
    'Israel': 'Israel',
    'Jordania': 'Jordan',
    'Marruecos': 'Morocco',
    'Egipto': 'Egypt',
    'Sudáfrica': 'South Africa',
    'Kenia': 'Kenya',
    'Tanzania': 'Tanzania',
    'Nigeria': 'Nigeria',
    'Ghana': 'Ghana',
    'Cuba': 'Cuba',
    'República Dominicana': 'Dominican Republic',
    'Puerto Rico': 'Puerto Rico',
    'Costa Rica': 'Costa Rica',
    'Panamá': 'Panama',
    'Guatemala': 'Guatemala',
    'Honduras': 'Honduras',
    'El Salvador': 'El Salvador',
    'Nicaragua': 'Nicaragua',
  };

  static const Map<String, String> _cityTranslations = {
    // Italy
    'Roma': 'Rome',
    'Venecia': 'Venice',
    'Florencia': 'Florence',
    'Milán': 'Milan',
    'Nápoles': 'Naples',
    'Turín': 'Turin',
    'Génova': 'Genoa',
    'Bolonia': 'Bologna',
    'Palermo': 'Palermo',
    // France
    'París': 'Paris',
    'Marsella': 'Marseille',
    'Lyon': 'Lyon',
    'Niza': 'Nice',
    'Burdeos': 'Bordeaux',
    'Estrasburgo': 'Strasbourg',
    'Nantes': 'Nantes',
    // Germany
    'Berlín': 'Berlin',
    'Múnich': 'Munich',
    'Hamburgo': 'Hamburg',
    'Colonia': 'Cologne',
    'Fráncfort': 'Frankfurt',
    'Stuttgart': 'Stuttgart',
    'Düsseldorf': 'Düsseldorf',
    'Dresde': 'Dresden',
    // UK
    'Londres': 'London',
    'Manchester': 'Manchester',
    'Birmingham': 'Birmingham',
    'Edimburgo': 'Edinburgh',
    'Glasgow': 'Glasgow',
    'Liverpool': 'Liverpool',
    'Bristol': 'Bristol',
    'Leeds': 'Leeds',
    // Austria
    'Viena': 'Vienna',
    'Salzburgo': 'Salzburg',
    'Innsbruck': 'Innsbruck',
    // Czech Republic
    'Praga': 'Prague',
    'Brno': 'Brno',
    // Belgium
    'Bruselas': 'Brussels',
    'Brujas': 'Bruges',
    'Gante': 'Ghent',
    'Amberes': 'Antwerp',
    // Netherlands
    'Ámsterdam': 'Amsterdam',
    'Rotterdam': 'Rotterdam',
    'La Haya': 'The Hague',
    'Utrecht': 'Utrecht',
    // Poland
    'Varsovia': 'Warsaw',
    'Cracovia': 'Kraków',
    'Gdansk': 'Gdańsk',
    'Wroclaw': 'Wrocław',
    // Hungary
    'Budapest': 'Budapest',
    // Russia
    'Moscú': 'Moscow',
    'San Petersburgo': 'Saint Petersburg',
    // Turkey
    'Estambul': 'Istanbul',
    'Ankara': 'Ankara',
    'Antalya': 'Antalya',
    // Greece
    'Atenas': 'Athens',
    'Tesalónica': 'Thessaloniki',
    // Portugal
    'Lisboa': 'Lisbon',
    'Oporto': 'Porto',
    'Faro': 'Faro',
    // Spain (mostly same, but some differ)
    'Sevilla': 'Seville',
    'Málaga': 'Malaga',
    'Córdoba': 'Córdoba',
    'Zaragoza': 'Zaragoza',
    // Nordic
    'Copenhague': 'Copenhagen',
    'Estocolmo': 'Stockholm',
    'Oslo': 'Oslo',
    'Helsinki': 'Helsinki',
    'Bergen': 'Bergen',
    'Gotemburgo': 'Gothenburg',
    // Ireland
    'Dublín': 'Dublin',
    // Switzerland
    'Ginebra': 'Geneva',
    'Zúrich': 'Zurich',
    'Berna': 'Bern',
    'Basilea': 'Basel',
    // Asia
    'Tokio': 'Tokyo',
    'Seúl': 'Seoul',
    'Pekín': 'Beijing',
    'Shanghái': 'Shanghai',
    'Hong Kong': 'Hong Kong',
    'Bangkok': 'Bangkok',
    'Singapur': 'Singapore',
    'Kuala Lumpur': 'Kuala Lumpur',
    'Yakarta': 'Jakarta',
    'Manila': 'Manila',
    'Bombay': 'Mumbai',
    'Mumbai': 'Mumbai',
    'Delhi': 'Delhi',
    'Nueva Delhi': 'New Delhi',
    'Calcuta': 'Kolkata',
    'Dubái': 'Dubai',
    'Abu Dabi': 'Abu Dhabi',
    'El Cairo': 'Cairo',
    'Marrakech': 'Marrakech',
    'Casablanca': 'Casablanca',
    // Oceania
    'Sídney': 'Sydney',
    'Melbourne': 'Melbourne',
    'Brisbane': 'Brisbane',
    'Perth': 'Perth',
    'Auckland': 'Auckland',
    // Americas
    'Nueva York': 'New York',
    'Los Ángeles': 'Los Angeles',
    'Chicago': 'Chicago',
    'Houston': 'Houston',
    'Miami': 'Miami',
    'Las Vegas': 'Las Vegas',
    'San Francisco': 'San Francisco',
    'Washington D.C.': 'Washington D.C.',
    'Boston': 'Boston',
    'Seattle': 'Seattle',
    'Toronto': 'Toronto',
    'Vancouver': 'Vancouver',
    'Montreal': 'Montreal',
    'Ciudad de México': 'Mexico City',
    'México D.F.': 'Mexico City',
    'Guadalajara': 'Guadalajara',
    'Cancún': 'Cancún',
    'Buenos Aires': 'Buenos Aires',
    'Córdoba (Argentina)': 'Córdoba',
    'São Paulo': 'São Paulo',
    'Río de Janeiro': 'Rio de Janeiro',
    'Bogotá': 'Bogotá',
    'Medellín': 'Medellín',
    'Lima': 'Lima',
    'Santiago': 'Santiago',
    'La Habana': 'Havana',
    'Santo Domingo': 'Santo Domingo',
    // Africa
    'Nairobi': 'Nairobi',
    'Lagos': 'Lagos',
    'Johannesburgo': 'Johannesburg',
    'Ciudad del Cabo': 'Cape Town',
  };

  static const Map<String, String> _serviceTranslations = {
    'WiFi gratis': 'Free WiFi',
    'Parking': 'Parking',
    'Parking gratis': 'Free parking',
    'Piscina': 'Swimming pool',
    'Gimnasio': 'Gym',
    'Restaurante': 'Restaurant',
    'Servicio de habitaciones': 'Room service',
    'Recepción 24 horas': '24-hour reception',
    'Spa y centro de bienestar': 'Spa & wellness',
    'Traslado aeropuerto': 'Airport shuttle',
    'Adaptado para sillas de ruedas': 'Wheelchair accessible',
    'Estación de carga de vehículos eléctricos': 'EV charging station',
    'Bañera de hidromasaje / jacuzzi': 'Whirlpool / Jacuzzi',
    'Habitaciones sin humo': 'Non-smoking rooms',
    'Admite mascotas': 'Pets allowed',
    'Solo adultos': 'Adults only',
    'Desayuno incluido': 'Breakfast included',
    'Cancelación gratis': 'Free cancellation',
    'Zona favorita de los clientes': 'Guest favourite',
    'Fantástico: 9 o más': 'Superb: 9+',
    'Muy bien: 8 o más': 'Very good: 8+',
    // Room types
    'Habitación': 'Room',
    'Habitación Estándar': 'Standard Room',
    'Habitación Doble': 'Double Room',
    'Habitación Individual': 'Single Room',
    'Habitación Familiar': 'Family Room',
    'Habitación Superior': 'Superior Room',
    'Habitación Deluxe': 'Deluxe Room',
    'Suite': 'Suite',
    'Suite Junior': 'Junior Suite',
    'Suite Deluxe': 'Deluxe Suite',
    'Suite Ejecutiva': 'Executive Suite',
    'Suite Presidencial': 'Presidential Suite',
    'Suite Familiar': 'Family Suite',
    'Estándar': 'Standard',
    'Doble': 'Double',
    'Individual': 'Single',
    'Familiar': 'Family',
    'Superior': 'Superior',
    'Deluxe': 'Deluxe',
    'Ejecutiva': 'Executive',
  };

  static const Map<String, Map<String, String>> _translations = {
    'es': {
      // Login
      'login_title': 'Iniciar Sesión',
      'login_username': 'Email o usuario',
      'login_password': 'Contraseña',
      'login_button': 'Iniciar Sesión',
      'login_no_account': '¿No tienes cuenta?',
      'login_register': 'Regístrate',
      'login_2fa_title': 'Verificación en dos pasos',
      'login_2fa_subtitle':
          'Introduce el código de 6 dígitos de tu app de autenticación',
      'login_2fa_hint': 'Código de 6 dígitos',
      'login_2fa_button': 'Verificar',
      'login_2fa_invalid': 'Código inválido. Inténtalo de nuevo.',
      'login_2fa_back': 'Volver al inicio de sesión',
      // Settings
      'settings_title': 'Ajustes',
      'settings_account': 'Información de la Cuenta',
      'settings_username': 'Nombre de usuario',
      'settings_role': 'Rol / Permisos',
      'settings_regional': 'Preferencias Regionales',
      'settings_currency': 'Moneda local',
      'settings_language': 'Idioma / Language',
      'settings_customization': 'Personalización',
      'settings_dark_mode': 'Modo Oscuro',
      'settings_dark_mode_on': 'Invertido (Oscuro)',
      'settings_dark_mode_off': 'Estándar (Claro)',
      'settings_activate': 'Activar',
      'settings_deactivate': 'Desactivar',
      'settings_security': 'Seguridad y Privacidad',
      'settings_change_password': 'Cambiar Contraseña',
      'settings_notifications': 'Notificaciones Push',
      'settings_delete_account': 'Eliminar cuenta',
      'settings_2fa': 'Verificación en dos pasos (2FA)',
      'settings_2fa_enabled': '2FA activado · Cuenta protegida',
      'settings_2fa_disabled': 'Sin protección adicional',
      'settings_2fa_description':
          'Añade una capa extra de seguridad a tu cuenta',
      'settings_2fa_setup': 'Configurar 2FA',
      'settings_2fa_disable': 'Desactivar 2FA',
      // 2FA Setup Page
      '2fa_setup_title': 'Configurar 2FA',
      '2fa_scan_qr': 'Escanea el código QR',
      '2fa_scan_instructions':
          'Usa Google Authenticator, Authy u otra app compatible para escanear el código QR y añadir SkyTrip.',
      '2fa_manual_entry': 'O introduce la clave manualmente:',
      '2fa_verify_title': 'Verificar configuración',
      '2fa_verify_hint': 'Código de 6 dígitos',
      '2fa_verify_button': 'Activar 2FA',
      '2fa_verify_description':
          'Introduce el código de tu app de autenticación para confirmar que la configuración es correcta.',
      '2fa_success': '¡2FA activado correctamente!',
      '2fa_invalid_code':
          'Código incorrecto. Asegúrate de que la hora de tu dispositivo es correcta.',
      '2fa_disabled_success': '2FA desactivado correctamente',
      // Common
      'cancel': 'Cancelar',
      'save': 'Guardar',
      'retry': 'Reintentar',
      'loading': 'Cargando...',
      'error_connection': 'No se pudo conectar con el servidor.',
      'ok': 'Aceptar',
      'field_required': 'Campo requerido',
      'email_invalid': 'Email inválido',
      // Login page extra
      'login_tagline': 'Tu próxima aventura te espera',
      'login_about': 'Acerca de SkyTrip',
      // Register
      'register_title': 'Crear Cuenta',
      'register_join': 'Únete a SkyTrip',
      'register_explore': 'Crea tu cuenta y empieza a explorar el mundo',
      'register_secure_data': 'Datos seguros',
      'register_no_spam': 'Sin spam',
      'register_free': 'Gratis',
      'register_account_info': 'Información de cuenta',
      'register_username': 'Nombre de usuario',
      'register_email': 'Correo electrónico',
      'register_password': 'Contraseña',
      'register_confirm_password': 'Confirmar contraseña',
      'register_accept_terms': 'Acepto los ',
      'register_terms_link': 'Términos y Condiciones',
      'register_terms_suffix': ' de SkyTrip',
      'register_accept_terms_alert': 'Debes aceptar los términos y condiciones',
      'register_btn': 'Crear cuenta',
      'register_welcome': '¡Bienvenido/a a SkyTrip!',
      'register_have_account': '¿Ya tienes cuenta? ',
      'register_sign_in': 'Inicia sesión',
      'register_min_username': 'Mínimo 3 caracteres',
      'register_min_password': 'Mínimo 6 caracteres',
      'register_password_mismatch': 'Las contraseñas no coinciden',
      // Hotels / Alojamientos
      'hotels_title': 'Todos los Alojamientos',
      'hotels_in_city': 'Hoteles en ',
      'hotels_in_country': 'Hoteles en ',
      'hotels_search_hint': 'Buscar por nombre o ciudad...',
      'hotels_no_results': 'No hay alojamientos disponibles',
      'hotels_all_stars': 'Todas',
      'hotels_stars': 'estrellas',
      'hotels_price_range_title': 'Rango de Precio',
      'hotels_min_stars_title': 'Estrellas Mínimas',
      'hotels_apply': 'Aplicar',
      'hotels_per_night': '/ noche',
      // Reviews
      'reviews_title': 'Valoraciones',
      'reviews_traveler_opinions': 'Opiniones de viajeros',
      'reviews_write': 'Escribe una opinión',
      'reviews_share': 'Comparte tu experiencia con otros viajeros',
      'reviews_hotel_label': 'Hotel',
      'reviews_select_hotel': 'Selecciona el hotel',
      'reviews_rating': 'Tu puntuación',
      'reviews_comment': 'Tu comentario',
      'reviews_comment_hint': 'Cuenta tu experiencia: servicio, limpieza, ubicación…',
      'reviews_publish': 'Publicar opinión',
      'reviews_none': 'Todavía no hay opiniones',
      'reviews_be_first': '¡Sé el primero en compartir tu experiencia!',
      'reviews_write_btn': 'Escribir opinión',
      'reviews_select_hotel_alert': 'Selecciona un hotel para valorar.',
      'reviews_add_comment_alert': 'Escribe un comentario antes de enviar.',
      'reviews_login_required': 'Debes iniciar sesión para valorar.',
      'reviews_thanks': '¡Gracias por tu valoración!',
      'reviews_submit_error': 'No se pudo enviar la valoración. Inténtalo de nuevo.',
      'reviews_already_reviewed': 'Ya has valorado este hotel anteriormente.',
      'reviews_delete_title': 'Eliminar reseña',
      'reviews_delete_confirm': '¿Seguro que quieres eliminar esta reseña?',
      'reviews_delete_btn': 'Eliminar',
      'reviews_count_label': 'opiniones',
      'reviews_deleted': 'Reseña eliminada.',
      'reviews_delete_error': 'No se pudo eliminar la reseña.',
      'reviews_update_tooltip': 'Actualizar',
      'reviews_search_hint': 'Buscar por hotel, usuario o comentario…',
      'reviews_search_hotel_hint': 'Buscar hotel…',
      'reviews_no_results': 'No hay reseñas que coincidan con la búsqueda.',
      'rating_exceptional': 'Excepcional',
      'rating_very_good': 'Muy bueno',
      'rating_good': 'Bueno',
      'rating_fair': 'Regular',
      'rating_bad': 'Malo',
      // Contact / Atención al cliente
      'contact_title': 'Atención al Cliente',
      'contact_subtitle': 'Estamos aquí para ayudarte',
      'contact_availability': 'Soporte disponible ahora · Tiempo de respuesta < 2h',
      'contact_channels': 'Canales de contacto',
      'contact_send_message_section': 'Envíanos un mensaje',
      'contact_faq': 'Preguntas frecuentes',
      'contact_response_times': 'Tiempos de respuesta',
      'contact_form_title': 'Cuéntanos en qué podemos ayudarte',
      'contact_name': 'Nombre',
      'contact_subject': 'Asunto',
      'contact_message': 'Mensaje',
      'contact_send_btn': 'Enviar mensaje',
      'contact_sent_title': '¡Mensaje enviado!',
      'contact_sent_body': 'Hemos recibido tu mensaje y te responderemos en menos de 24 horas.',
      'contact_send_another': 'Enviar otro mensaje',
      'contact_error_send': 'Error al enviar el mensaje. Inténtalo de nuevo.',
      'contact_error_connection': 'Error de conexión. Verifica tu red.',
      'contact_message_min': 'El mensaje debe tener al menos 10 caracteres',
      'contact_badge_online': 'En línea',
      'contact_rt_chat': 'Chat en vivo',
      'contact_rt_phone': 'Teléfono',
      'contact_rt_whatsapp': 'WhatsApp',
      'contact_rt_email': 'Correo electrónico',
      'contact_rt_immediate': 'Inmediato',
      'contact_rt_247': '24/7 disponible',
      'contact_rt_1h': 'Menos de 1 hora',
      'contact_rt_24h': 'Menos de 24 horas',
      // Settings dialogs
      'settings_current_password': 'Contraseña actual',
      'settings_new_password': 'Nueva contraseña',
      'settings_password_updated': 'Contraseña actualizada correctamente',
      'settings_delete_title': '¿Eliminar cuenta?',
      'settings_delete_content': 'Esta acción es permanente y borrará todos tus datos. No podrás recuperar tu cuenta.',
      'settings_delete_btn': 'Eliminar definitivamente',
      'settings_delete_error': 'Error al eliminar la cuenta',
      'settings_2fa_disable_title': 'Desactivar 2FA',
      'settings_2fa_disable_content': 'Tu cuenta quedará menos protegida. ¿Deseas continuar?',
      'settings_2fa_disable_confirm': 'Desactivar',
      'settings_currency_changed': 'Moneda cambiada a ',
      // 2FA setup page extra
      'twofa_step1': 'PASO 1 · ESCANEAR',
      'twofa_step2': 'PASO 2 · VERIFICAR',
      'twofa_copy_hint': 'Toca para copiar la clave',
      'twofa_copied': 'Clave copiada al portapapeles',
      'twofa_info_banner': 'La autenticación en dos pasos protege tu cuenta incluso si tu contraseña se ve comprometida.',
      // Drawer
      'drawer_calendar': 'Calendario',
      'drawer_my_bookings': 'Mis Reservas',
      'drawer_favorites': 'Favoritos',
      'drawer_profile': 'Mi Perfil',
      'drawer_admin': 'Administrar',
      'drawer_explore': 'Explorar',
      'drawer_destinations': 'Destinos del mundo',
      'drawer_logout': 'Cerrar sesión',
      'drawer_goodbye': '¡Hasta pronto, {name}!',
      // Home - hero
      'home_accommodations_worldwide': 'alojamientos en todo el mundo',
      'home_hero_title': 'Encuentra el alojamiento\nperfecto para ti',
      'home_hero_subtitle': 'Compara precios, lee opiniones y reserva sin complicaciones.',
      // Home - search bar
      'home_search_hint': 'Destino, ciudad o hotel',
      'home_city': 'Ciudad',
      'home_country': 'País',
      'home_calendar': 'Calendario',
      'home_dates': 'Fechas',
      'home_days': 'días',
      'home_guests': 'Huéspedes',
      'home_search_btn': 'Buscar',
      // Quick filters
      'home_filter_all': 'Todos',
      'home_filter_pool': 'Piscina',
      'home_filter_breakfast': 'Desayuno',
      'home_filter_wifi': 'WiFi',
      'home_filter_parking': 'Parking',
      'home_filter_pets': 'Mascotas',
      'home_filter_spa': 'Spa',
      'home_filter_nosmoking': 'Sin humo',
      // Sort
      'home_sort_low_price': 'Precio más bajo',
      'home_sort_best_rating': 'Mejor valoración',
      'home_sort_high_price': 'Precio más alto',
      'home_sort_near_center': 'Más cerca del centro',
      // Filters
      'home_filters': 'Filtros avanzados',
      'home_active': 'activo',
      'home_actives': 'activos',
      'home_clear_all': 'Limpiar todo',
      'home_sort_by': 'Ordenar por',
      'home_all_categories': 'Todas las categorías',
      'home_stars_label': '+ estrellas',
      'home_category': 'Categoría',
      'home_max_price_label': 'Precio máximo',
      'home_min_rating_label': 'Valoración mínima',
      'home_center_label': 'Centro: hasta',
      'home_airport_label': 'Aeropuerto: hasta',
      'home_km': 'km',
      'home_services_label': 'Servicios del alojamiento',
      'home_select_services': 'Seleccionar servicios',
      'home_service_singular': 'servicio seleccionado',
      'home_service_plural': 'servicios seleccionados',
      'home_clear': 'Limpiar',
      // Guests dialog
      'home_select_guests': 'Seleccionar huéspedes',
      'home_adult': 'Adulto',
      'home_child': 'Niño',
      'home_years': 'años',
      // Popular destinations
      'home_popular_destinations': 'Destinos populares',
      'home_popular_subtitle': 'Los viajeros eligen estos destinos',
      'home_hotel_singular': 'hotel',
      'home_hotel_plural': 'hoteles',
      'home_from': 'Desde',
      // Stats strip
      'home_stat_hotels': 'Hoteles',
      'home_stat_countries': 'Países',
      'home_stat_support': 'Soporte',
      'home_stat_secure': 'Seguro',
      // Results
      'home_load_error': 'No se pudieron cargar los alojamientos. Comprueba tu conexión.',
      'home_no_results': 'No hay hoteles que encajen con esos filtros.',
      'home_load_more': 'Ver más',
      'home_accommodations_found': 'alojamiento encontrado',
      'home_accommodations_found_p': 'alojamientos encontrados',
      // Cart
      'home_your_bookings': 'Tus reservas',
      'home_empty_cart': 'Todavía no has añadido ningún hotel.',
      'home_refund': 'Reembolsar',
      // Login required
      'home_login_required': 'Inicia sesión',
      'home_login_favorites': 'Inicia sesión para guardar tus hoteles favoritos.',
      'home_login_continue': 'Inicia sesión para continuar.',
      // Favorites
      'home_removed_fav': 'eliminado de favoritos',
      'home_added_fav': 'añadido a favoritos',
      'home_fav_error': 'No se pudo guardar el favorito en la base de datos.',
      // Actions / errors
      'home_insufficient_balance': 'Saldo insuficiente para este viaje.',
      'home_added_booking': 'añadido a tus reservas.',
      // Why SkyTrip section
      'home_why_title': '¿Por qué elegir SkyTrip?',
      'home_why_subtitle': 'Millones de viajeros nos eligen cada año',
      'home_benefit_1_title': 'Alojamientos verificados',
      'home_benefit_1_desc': 'Todos los hoteles pasan por nuestro proceso de verificación de calidad.',
      'home_benefit_2_title': 'Mejor precio garantizado',
      'home_benefit_2_desc': 'Si encuentras un precio mejor, te igualamos la oferta sin preguntas.',
      'home_benefit_3_title': 'Cancelación flexible',
      'home_benefit_3_desc': 'Cancela gratis hasta 24h antes del check-in en la mayoría de hoteles.',
      'home_benefit_4_title': 'Atención 24/7',
      'home_benefit_4_desc': 'Nuestro equipo de soporte está disponible a cualquier hora del día.',
      // Promo banner
      'home_promo_badge': '🔥  OFERTA FLASH',
      'home_promo_fallback': 'Las mejores\nofertas del día',
      'home_promo_subtitle': 'Precios para fechas flexibles',
      'home_promo_btn': 'Ver ofertas',
      // Recently viewed
      'home_recently_viewed': 'Vistos recientemente',
      'home_recently_subtitle': 'Continúa donde lo dejaste',
      // Hotel card
      'home_per_night': '/noche',
      'home_per_night_label': 'por noche',
      'home_nights': 'noches',
      'home_total': 'total',
      'home_see_avail': 'Ver disponibilidad',
      'home_see': 'Ver',
      'home_km_airport': 'km aer.',
      'home_guests_abbr': 'huésp.',
      'home_free_cancel': '✓ Cancela gratis',
      'home_breakfast_incl': '🍳 Desayuno incl.',
      'home_wifi_free': '📶 WiFi gratis',
      'home_hotel_fallback_desc': 'Un alojamiento bien situado para tu próxima escapada.',
      // Destinos page
      'destinos_title': 'Destinos',
      'destinos_hero_title': 'Explora destinos',
      'destinos_hero_subtitle': 'Descubre los mejores lugares del mundo',
      'destinos_search_hint': 'Buscar ciudad o país…',
      'destinos_count_s': 'destino disponible',
      'destinos_count_p': 'destinos disponibles',
      'destinos_empty': 'No se encontraron destinos',
      'destinos_error_load': 'Error al cargar destinos. Inténtalo de nuevo.',
      'destinos_error_server': 'Respuesta inesperada del servidor.',
      'destinos_error_connection': 'No se pudo conectar con el servidor. Comprueba tu conexión.',
      'destinos_see_hotels': 'Ver hoteles',
      'destinos_hotel_s': 'hotel',
      'destinos_hotel_p': 'hoteles',
      'destinos_unknown_city': 'Ciudad desconocida',
      'destinos_unknown_country': 'País desconocido',
      // Mis Reservas page
      'reservas_refresh': 'Actualizar',
      'reservas_tab_active': 'Activas',
      'reservas_tab_history': 'Historial',
      'reservas_tab_cancelled': 'Canceladas',
      'reservas_total_invested': 'Total invertido en viajes',
      'reservas_label': 'reservas',
      'reservas_error_load': 'Error al cargar reservas. Inténtalo de nuevo.',
      'reservas_cancel_title': 'Cancelar reserva',
      'reservas_cancel_confirm': '¿Estás seguro de que quieres cancelar esta reserva? Esta acción no se puede deshacer.',
      'reservas_keep': 'Mantener',
      'reservas_cancelled_ok': 'Reserva cancelada correctamente',
      'reservas_cancel_error': 'No se pudo cancelar la reserva.',
      'reservas_cancel_conn_error': 'Error de conexión al cancelar la reserva.',
      'reservas_confirmed': 'Reserva confirmada',
      'reservas_completed': 'Estancia completada',
      'reservas_today': '¡Hoy!',
      'reservas_in_days_s': 'En {n} día',
      'reservas_in_days_p': 'En {n} días',
      'reservas_empty_active': 'No tienes reservas activas',
      'reservas_empty_active_sub': 'Reserva un hotel y aparecerá aquí.',
      'reservas_empty_history': 'Sin historial de reservas',
      'reservas_empty_history_sub': 'Las reservas pasadas aparecerán aquí.',
      'reservas_empty_cancelled': 'Sin reservas canceladas',
      'reservas_empty_cancelled_sub': 'No has cancelado ninguna reserva.',
      'reservas_checkin': 'Check-in',
      'reservas_checkout': 'Check-out',
      'reservas_duration': 'Duración',
      'reservas_night_s': 'noche',
      'reservas_night_p': 'noches',
      'reservas_person_s': 'persona',
      'reservas_person_p': 'personas',
      'reservas_total_price': 'precio total',
      'reservas_btn_cancel': 'Cancelar',
      // Favoritos page
      'fav_title': 'Mis Favoritos',
      'fav_empty_title': 'Aún no tienes favoritos',
      'fav_empty_sub': 'Guarda tus hoteles favoritos para encontrarlos fácilmente después.',
      'fav_search_hotels': 'Buscar hoteles',
      'fav_error_load': 'Error al cargar favoritos. Inténtalo de nuevo.',
      'fav_see': 'Ver',
      // Profile page
      'profile_title': 'Mi Perfil',
      'profile_edit_tooltip': 'Editar perfil',
      'profile_admin': 'Administrador',
      'profile_traveler': 'Viajero',
      'profile_stat_bookings': 'Reservas',
      'profile_stat_favorites': 'Favoritos',
      'profile_stat_reviews': 'Valoraciones',
      'profile_section_personal': 'Información personal',
      'profile_section_extra': 'Datos adicionales',
      'profile_section_account': 'Cuenta',
      'profile_username': 'Nombre de usuario',
      'profile_email': 'Correo electrónico',
      'profile_address': 'Dirección',
      'profile_birth_country': 'País de nacimiento',
      'profile_birth_date': 'Fecha de nacimiento',
      'profile_required': 'Campo requerido',
      'profile_email_invalid': 'Email inválido',
      'profile_date_format': 'Formato: YYYY-MM-DD',
      'profile_year_invalid': 'Año inválido',
      'profile_month_invalid': 'Mes inválido',
      'profile_day_invalid': 'Día inválido',
      'profile_save': 'Guardar cambios',
      'profile_change_password': 'Cambiar contraseña',
      'profile_2fa': 'Autenticación en dos pasos',
      'profile_logout': 'Cerrar sesión',
      'profile_updated_ok': 'Perfil actualizado correctamente',
      'profile_updated_error': 'Error al actualizar perfil',
      'profile_connection_error': 'Error de conexión',
      // Footer
      'footer_description': 'Compara alojamientos, filtra con\nprecisión y reserva sin complicaciones.',
      'footer_terms': 'Condiciones',
      'footer_support': 'Atención al cliente',
      'footer_destinations': 'Destinos',
      'footer_accommodations': 'Alojamientos',
      'footer_bookings': 'Mis Reservas',
      'footer_favorites': 'Favoritos',
      'footer_reviews': 'Valoraciones',
      // Search sentinels
      'home_all_cities': 'Todas',
      'home_all_countries': 'Todos',
      // About us page
      'about_title': 'Sobre Nosotros',
      'about_hero_title': 'Sobre nosotros',
      'about_hero_subtitle': 'Conoce nuestra historia y misión',
      'about_stat_hotels': 'Hoteles',
      'about_stat_countries': 'Países',
      'about_stat_rating': 'Valoración',
      'about_stat_support': 'Soporte',
      'about_section_history': 'Nuestra historia',
      'about_history_card_title': 'De aula a proyecto real',
      'about_history_p1': 'Nacida en un aula de Desarrollo de Aplicaciones Multiplataforma (DAM), SkyTrip comenzó como un pequeño proyecto entre estudiantes apasionados por la tecnología y la exploración. Lo que empezó con líneas de código y mucho café, se ha convertido en una visión para transformar la manera en que las personas descubren su próximo destino.',
      'about_history_p2': 'Desde nuestros primeros prototipos hasta la plataforma que ves hoy, cada línea de código ha sido escrita con una idea en mente: hacer que viajar sea accesible, sencillo y emocionante para todos.',
      'about_section_mission': 'Nuestra misión',
      'about_mission_quote': 'En SkyTrip creemos que viajar no es solo moverse de un punto A a un punto B, sino la experiencia que ocurre entre medias.',
      'about_mission_body': 'Nos dedicamos a simplificar la complejidad de planificar viajes, ofreciendo una plataforma intuitiva donde la inspiración se encuentra con la facilidad de uso. Desde las calles empedradas de Roma hasta los rascacielos de Tokio, nuestra base de datos crece cada día para traerte las mejores opciones al mejor precio.',
      'about_section_values': 'Nuestros valores',
      'about_value1_title': 'Confianza',
      'about_value1_body': 'Precios transparentes y sin cargos ocultos en cada reserva.',
      'about_value2_title': 'Innovación',
      'about_value2_body': 'Mejoramos continuamente la experiencia con tecnología punta.',
      'about_value3_title': 'Accesibilidad',
      'about_value3_body': 'Viajar es para todos. Trabajamos para eliminar barreras.',
      'about_value4_title': 'Sostenibilidad',
      'about_value4_body': 'Promovemos el turismo responsable con el planeta.',
      'about_section_team': 'El equipo',
      'about_section_tech': 'Tecnología',
      'about_tech_title': 'Construido con tecnología moderna',
      'about_cta_title': '¿Listo para despegar?',
      'about_cta_subtitle': 'Descubre miles de hoteles en más de 50 países. Tu próxima aventura empieza aquí.',
      'about_cta_button': 'Explorar hoteles',
      // Condiciones page
      'terms_title': 'Términos y Condiciones',
      'terms_page_title': 'Términos y Condiciones de SkyTrip',
      'terms_contact_title': 'Contacto',
      'terms_contact_body': 'Para cualquier duda sobre estos términos, puede contactarnos a través de nuestra página de Atención al Cliente.',
      // Login extra
      'login_error_empty': 'Por favor, introduce tu usuario y contraseña.',
      // Trip detail page
      'trip_score_label': 'Puntuación general',
      'trip_per_night': 'por noche',
      'trip_per_night_short': '/noche',
      'trip_nights': 'noches',
      'trip_total': 'total',
      'trip_about': 'Sobre este alojamiento',
      'trip_description_original_lang': 'Descripción en idioma original',
      'trip_services': 'Servicios e instalaciones',
      'trip_location': 'Ubicación',
      'trip_city_center': 'Centro de la ciudad',
      'trip_nearest_airport': 'Aeropuerto más cercano',
      'trip_available_rooms': 'Habitaciones disponibles',
      'trip_searching_for': 'Buscando para',
      'trip_no_rooms_title': 'Sin habitaciones disponibles',
      'trip_no_rooms_sub': 'No hay habitaciones registradas para este hotel.',
      'trip_guest_reviews': 'Opiniones de huéspedes',
      'trip_no_reviews_title': 'Sin opiniones todavía',
      'trip_no_reviews_sub': 'Sé el primero en valorar este hotel.',
      'trip_house_rules': 'Normas del alojamiento',
      'trip_checkin_from': 'A partir de las 15:00',
      'trip_checkout_before': 'Antes de las 12:00',
      'trip_smoking_no': 'No permitido',
      'trip_pets_consult': 'Consultar con el hotel',
      'trip_parties_no': 'No permitidas',
      'trip_free_cancel_24h': 'Gratis hasta 24 h antes',
      'trip_policy_smoking': 'Fumar',
      'trip_policy_parties': 'Fiestas',
      'trip_policy_cancellation': 'Cancelación',
      'trip_review_today': 'Hoy',
      'trip_review_yesterday': 'Ayer',
      'trip_days_ago_pre': 'Hace',
      'trip_days_ago_suf': 'días',
      'trip_share_tooltip': 'Compartir',
      'trip_share_copied': 'Enlace copiado',
      'trip_edit_tooltip': 'Editar hotel',
      'trip_settings_tooltip': 'Ajustes',
      'trip_login_title': 'Inicia sesión',
      'trip_login_to_book': 'Necesitas una cuenta para reservar. ¿Quieres iniciar sesión?',
      'trip_room_default': 'Habitación',
      'trip_room_recommended': 'RECOMENDADA',
      'trip_room_insuf_cap': 'CAPACIDAD INSUFICIENTE',
      'trip_room_wifi': 'WiFi gratis',
      'trip_room_breakfast': 'Desayuno',
      'trip_room_ac': 'Aire acond.',
      'trip_room_jacuzzi': 'Jacuzzi',
      'trip_room_book': 'Reservar',
      'trip_room_unavailable': 'No disponible',
      'trip_no_hotel_id': 'No se pudo identificar el hotel.',
      'trip_error_rooms': 'Error al cargar habitaciones',
      'trip_error_server': 'No se pudo conectar con el servidor.',
      'trip_rating_exceptional': 'Excepcional',
      'trip_rating_fantastic': 'Fantástico',
      'trip_rating_very_good': 'Muy bueno',
      'trip_rating_good': 'Bueno',
      'trip_rating_fair': 'Aceptable',
      'trip_rating_correct': 'Correcto',
      'trip_up_to': 'Hasta',
      'trip_guests': 'huéspedes',
      'trip_km_center': 'km del centro',
      'trip_km_airport': 'km aeropuerto',
      'trip_stars_label': 'estrellas',
      'trip_no_category': 'Sin categoría',
      'trip_you_need': 'necesitas',
      'room_person_s': 'persona',
      'room_person_p': 'personas',
      'guest_adult_s': 'adulto',
      'guest_adult_p': 'adultos',
      'guest_child_s': 'niño',
      'guest_child_p': 'niños',
      // Hotel card (home)
      'card_free_cancel': '✓ Cancela gratis',
      'card_breakfast_incl': '🍳 Desayuno incl.',
      'card_wifi_free': '📶 WiFi gratis',
      // Carousels
      'carousel_fivestar_title': 'Hoteles 5 estrellas',
      'carousel_fivestar_subtitle': 'Lujo y excelencia garantizados',
      'carousel_centric_title': 'Hoteles céntricos',
      'carousel_centric_subtitle': 'En el corazón de la ciudad',
      'carousel_bestvalue_title': 'Mejor relación calidad-precio',
      'carousel_bestvalue_subtitle': 'Alta valoración, precio justo',
      // Confirmar reserva page
      'booking_title': 'Tramitar Compra',
      'booking_room_label': 'Habitación',
      'booking_full_name': 'Nombre completo',
      'booking_dni': 'DNI / NIF',
      'booking_phone': 'Teléfono',
      'booking_name_required': 'Introduce tu nombre',
      'booking_name_letters_only': 'Solo letras y espacios',
      'booking_dni_required': 'Introduce tu DNI',
      'booking_dni_invalid': 'DNI inválido: 8 números y una letra',
      'booking_phone_required': 'Introduce tu teléfono',
      'booking_phone_invalid': 'Teléfono inválido: 9 dígitos',
      'booking_dates_title': 'Fechas de Viaje',
      'booking_dates_placeholder': 'Selecciona tus fechas aquí',
      'booking_change_dates': 'Cambiar Fechas',
      'booking_accept_dates': 'Aceptar Fechas',
      'booking_dates_accepted': 'Fechas aceptadas',
      'booking_cancel_dates': 'Cancelar Fechas',
      'booking_go_back': 'Salir Atrás',
      'booking_price_summary': 'Resumen de Precios',
      'booking_price_night': 'Precio por noche',
      'booking_num_nights': 'Número de noches',
      'booking_total': 'Total',
      'booking_guests_title': 'Huéspedes seleccionados',
      'booking_need_crib': 'Necesita cuna',
      'booking_include_breakfast': 'Incluir desayuno',
      'booking_fix_errors': 'Corrige los errores del formulario.',
      'booking_select_dates': 'Por favor, selecciona las fechas del viaje.',
      'booking_confirmed': 'Reserva confirmada con éxito',
      'booking_error': 'Error al confirmar la reserva',
      'booking_confirm_btn': 'CONFIRMAR RESERVA',
      'booking_adult_label': 'Adulto',
      'booking_child_label': 'Niño',
      'booking_years': 'años',
      'booking_nights': 'noches',
    },
    'en': {
      // Login
      'login_title': 'Sign In',
      'login_username': 'Email or username',
      'login_password': 'Password',
      'login_button': 'Sign In',
      'login_no_account': "Don't have an account?",
      'login_register': 'Register',
      'login_2fa_title': 'Two-step verification',
      'login_2fa_subtitle':
          'Enter the 6-digit code from your authenticator app',
      'login_2fa_hint': '6-digit code',
      'login_2fa_button': 'Verify',
      'login_2fa_invalid': 'Invalid code. Please try again.',
      'login_2fa_back': 'Back to sign in',
      // Settings
      'settings_title': 'Settings',
      'settings_account': 'Account Information',
      'settings_username': 'Username',
      'settings_role': 'Role / Permissions',
      'settings_regional': 'Regional Preferences',
      'settings_currency': 'Local currency',
      'settings_language': 'Language / Idioma',
      'settings_customization': 'Customization',
      'settings_dark_mode': 'Dark Mode',
      'settings_dark_mode_on': 'Dark (Enabled)',
      'settings_dark_mode_off': 'Light (Standard)',
      'settings_activate': 'Enable',
      'settings_deactivate': 'Disable',
      'settings_security': 'Security & Privacy',
      'settings_change_password': 'Change Password',
      'settings_notifications': 'Push Notifications',
      'settings_delete_account': 'Delete account',
      'settings_2fa': 'Two-factor authentication (2FA)',
      'settings_2fa_enabled': '2FA enabled · Account protected',
      'settings_2fa_disabled': 'No additional protection',
      'settings_2fa_description':
          'Add an extra layer of security to your account',
      'settings_2fa_setup': 'Set up 2FA',
      'settings_2fa_disable': 'Disable 2FA',
      // 2FA Setup Page
      '2fa_setup_title': 'Set up 2FA',
      '2fa_scan_qr': 'Scan the QR code',
      '2fa_scan_instructions':
          'Use Google Authenticator, Authy or another compatible app to scan the QR code and add SkyTrip.',
      '2fa_manual_entry': 'Or enter the key manually:',
      '2fa_verify_title': 'Verify setup',
      '2fa_verify_hint': '6-digit code',
      '2fa_verify_button': 'Enable 2FA',
      '2fa_verify_description':
          'Enter the code from your authenticator app to confirm the setup is correct.',
      '2fa_success': '2FA successfully enabled!',
      '2fa_invalid_code':
          'Incorrect code. Make sure your device time is correct.',
      '2fa_disabled_success': '2FA successfully disabled',
      // Common
      'cancel': 'Cancel',
      'save': 'Save',
      'retry': 'Retry',
      'loading': 'Loading...',
      'error_connection': 'Could not connect to server.',
      'ok': 'OK',
      'field_required': 'Required field',
      'email_invalid': 'Invalid email',
      // Login page extra
      'login_tagline': 'Your next adventure awaits',
      'login_about': 'About SkyTrip',
      // Register
      'register_title': 'Create Account',
      'register_join': 'Join SkyTrip',
      'register_explore': 'Create your account and start exploring the world',
      'register_secure_data': 'Secure data',
      'register_no_spam': 'No spam',
      'register_free': 'Free',
      'register_account_info': 'Account information',
      'register_username': 'Username',
      'register_email': 'Email address',
      'register_password': 'Password',
      'register_confirm_password': 'Confirm password',
      'register_accept_terms': 'I accept the ',
      'register_terms_link': 'Terms and Conditions',
      'register_terms_suffix': ' of SkyTrip',
      'register_accept_terms_alert': 'You must accept the terms and conditions',
      'register_btn': 'Create account',
      'register_welcome': 'Welcome to SkyTrip!',
      'register_have_account': 'Already have an account? ',
      'register_sign_in': 'Sign in',
      'register_min_username': 'At least 3 characters',
      'register_min_password': 'At least 6 characters',
      'register_password_mismatch': 'Passwords do not match',
      // Hotels / Alojamientos
      'hotels_title': 'All Accommodations',
      'hotels_in_city': 'Hotels in ',
      'hotels_in_country': 'Hotels in ',
      'hotels_search_hint': 'Search by name or city...',
      'hotels_no_results': 'No accommodations available',
      'hotels_all_stars': 'All',
      'hotels_stars': 'stars',
      'hotels_price_range_title': 'Price Range',
      'hotels_min_stars_title': 'Minimum Stars',
      'hotels_apply': 'Apply',
      'hotels_per_night': '/ night',
      // Reviews
      'reviews_title': 'Reviews',
      'reviews_traveler_opinions': 'Traveler opinions',
      'reviews_write': 'Write a review',
      'reviews_share': 'Share your experience with fellow travelers',
      'reviews_hotel_label': 'Hotel',
      'reviews_select_hotel': 'Select hotel',
      'reviews_rating': 'Your rating',
      'reviews_comment': 'Your comment',
      'reviews_comment_hint': 'Share your experience: service, cleanliness, location…',
      'reviews_publish': 'Publish review',
      'reviews_none': 'No reviews yet',
      'reviews_be_first': 'Be the first to share your experience!',
      'reviews_write_btn': 'Write a review',
      'reviews_select_hotel_alert': 'Select a hotel to review.',
      'reviews_add_comment_alert': 'Write a comment before submitting.',
      'reviews_login_required': 'You must be logged in to review.',
      'reviews_thanks': 'Thank you for your review!',
      'reviews_submit_error': 'Could not submit review. Please try again.',
      'reviews_already_reviewed': 'You have already reviewed this hotel.',
      'reviews_delete_title': 'Delete review',
      'reviews_delete_confirm': 'Are you sure you want to delete this review?',
      'reviews_delete_btn': 'Delete',
      'reviews_count_label': 'reviews',
      'reviews_deleted': 'Review deleted.',
      'reviews_delete_error': 'Could not delete review.',
      'reviews_update_tooltip': 'Refresh',
      'reviews_search_hint': 'Search by hotel, user or comment…',
      'reviews_search_hotel_hint': 'Search hotel…',
      'reviews_no_results': 'No reviews match your search.',
      'rating_exceptional': 'Exceptional',
      'rating_very_good': 'Very good',
      'rating_good': 'Good',
      'rating_fair': 'Fair',
      'rating_bad': 'Bad',
      // Contact / Atención al cliente
      'contact_title': 'Customer Support',
      'contact_subtitle': 'We are here to help you',
      'contact_availability': 'Support available now · Response time < 2h',
      'contact_channels': 'Contact channels',
      'contact_send_message_section': 'Send us a message',
      'contact_faq': 'Frequently asked questions',
      'contact_response_times': 'Response times',
      'contact_form_title': 'Tell us how we can help you',
      'contact_name': 'Name',
      'contact_subject': 'Subject',
      'contact_message': 'Message',
      'contact_send_btn': 'Send message',
      'contact_sent_title': 'Message sent!',
      'contact_sent_body': 'We received your message and will reply within 24 hours.',
      'contact_send_another': 'Send another message',
      'contact_error_send': 'Error sending message. Please try again.',
      'contact_error_connection': 'Connection error. Check your network.',
      'contact_message_min': 'Message must be at least 10 characters',
      'contact_badge_online': 'Online',
      'contact_rt_chat': 'Live chat',
      'contact_rt_phone': 'Phone',
      'contact_rt_whatsapp': 'WhatsApp',
      'contact_rt_email': 'Email',
      'contact_rt_immediate': 'Immediate',
      'contact_rt_247': 'Available 24/7',
      'contact_rt_1h': 'Under 1 hour',
      'contact_rt_24h': 'Under 24 hours',
      // Settings dialogs
      'settings_current_password': 'Current password',
      'settings_new_password': 'New password',
      'settings_password_updated': 'Password updated successfully',
      'settings_delete_title': 'Delete account?',
      'settings_delete_content': 'This action is permanent and will delete all your data. You cannot recover your account.',
      'settings_delete_btn': 'Delete permanently',
      'settings_delete_error': 'Error deleting account',
      'settings_2fa_disable_title': 'Disable 2FA',
      'settings_2fa_disable_content': 'Your account will be less protected. Do you want to continue?',
      'settings_2fa_disable_confirm': 'Disable',
      'settings_currency_changed': 'Currency changed to ',
      // 2FA setup page extra
      'twofa_step1': 'STEP 1 · SCAN',
      'twofa_step2': 'STEP 2 · VERIFY',
      'twofa_copy_hint': 'Tap to copy the key',
      'twofa_copied': 'Key copied to clipboard',
      'twofa_info_banner': 'Two-factor authentication protects your account even if your password is compromised.',
      // Drawer
      'drawer_calendar': 'Calendar',
      'drawer_my_bookings': 'My Bookings',
      'drawer_favorites': 'Favorites',
      'drawer_profile': 'My Profile',
      'drawer_admin': 'Manage',
      'drawer_explore': 'Explore',
      'drawer_destinations': 'World destinations',
      'drawer_logout': 'Sign out',
      'drawer_goodbye': 'See you soon, {name}!',
      // Home - hero
      'home_accommodations_worldwide': 'accommodations worldwide',
      'home_hero_title': 'Find the perfect\naccommodation for you',
      'home_hero_subtitle': 'Compare prices, read reviews and book without hassle.',
      // Home - search bar
      'home_search_hint': 'Destination, city or hotel',
      'home_city': 'City',
      'home_country': 'Country',
      'home_calendar': 'Calendar',
      'home_dates': 'Dates',
      'home_days': 'days',
      'home_guests': 'Guests',
      'home_search_btn': 'Search',
      // Quick filters
      'home_filter_all': 'All',
      'home_filter_pool': 'Pool',
      'home_filter_breakfast': 'Breakfast',
      'home_filter_wifi': 'WiFi',
      'home_filter_parking': 'Parking',
      'home_filter_pets': 'Pets',
      'home_filter_spa': 'Spa',
      'home_filter_nosmoking': 'No smoking',
      // Sort
      'home_sort_low_price': 'Lowest price',
      'home_sort_best_rating': 'Best rating',
      'home_sort_high_price': 'Highest price',
      'home_sort_near_center': 'Nearest to center',
      // Filters
      'home_filters': 'Advanced filters',
      'home_active': 'active',
      'home_actives': 'active',
      'home_clear_all': 'Clear all',
      'home_sort_by': 'Sort by',
      'home_all_categories': 'All categories',
      'home_stars_label': '+ stars',
      'home_category': 'Category',
      'home_max_price_label': 'Max price',
      'home_min_rating_label': 'Min rating',
      'home_center_label': 'Center: up to',
      'home_airport_label': 'Airport: up to',
      'home_km': 'km',
      'home_services_label': 'Accommodation services',
      'home_select_services': 'Select services',
      'home_service_singular': 'service selected',
      'home_service_plural': 'services selected',
      'home_clear': 'Clear',
      // Guests dialog
      'home_select_guests': 'Select guests',
      'home_adult': 'Adult',
      'home_child': 'Child',
      'home_years': 'years',
      // Popular destinations
      'home_popular_destinations': 'Popular destinations',
      'home_popular_subtitle': 'Travelers choose these destinations',
      'home_hotel_singular': 'hotel',
      'home_hotel_plural': 'hotels',
      'home_from': 'From',
      // Stats strip
      'home_stat_hotels': 'Hotels',
      'home_stat_countries': 'Countries',
      'home_stat_support': 'Support',
      'home_stat_secure': 'Secure',
      // Results
      'home_load_error': 'Could not load accommodations. Check your connection.',
      'home_no_results': 'No hotels match those filters.',
      'home_load_more': 'Load more',
      'home_accommodations_found': 'accommodation found',
      'home_accommodations_found_p': 'accommodations found',
      // Cart
      'home_your_bookings': 'Your bookings',
      'home_empty_cart': "You haven't added any hotel yet.",
      'home_refund': 'Refund',
      // Login required
      'home_login_required': 'Sign in',
      'home_login_favorites': 'Sign in to save your favorite hotels.',
      'home_login_continue': 'Sign in to continue.',
      // Favorites
      'home_removed_fav': 'removed from favorites',
      'home_added_fav': 'added to favorites',
      'home_fav_error': 'Could not save favorite to database.',
      // Actions / errors
      'home_insufficient_balance': 'Insufficient balance for this trip.',
      'home_added_booking': 'added to your bookings.',
      // Why SkyTrip section
      'home_why_title': 'Why choose SkyTrip?',
      'home_why_subtitle': 'Millions of travelers choose us every year',
      'home_benefit_1_title': 'Verified accommodations',
      'home_benefit_1_desc': 'All hotels go through our quality verification process.',
      'home_benefit_2_title': 'Best price guaranteed',
      'home_benefit_2_desc': "If you find a better price, we'll match it, no questions asked.",
      'home_benefit_3_title': 'Flexible cancellation',
      'home_benefit_3_desc': 'Cancel free up to 24h before check-in at most hotels.',
      'home_benefit_4_title': '24/7 Support',
      'home_benefit_4_desc': 'Our support team is available at any time of day.',
      // Promo banner
      'home_promo_badge': '🔥  FLASH DEAL',
      'home_promo_fallback': "Today's best\ndeals",
      'home_promo_subtitle': 'Prices for flexible dates',
      'home_promo_btn': 'See deals',
      // Recently viewed
      'home_recently_viewed': 'Recently viewed',
      'home_recently_subtitle': 'Continue where you left off',
      // Hotel card
      'home_per_night': '/night',
      'home_per_night_label': 'per night',
      'home_nights': 'nights',
      'home_total': 'total',
      'home_see_avail': 'See availability',
      'home_see': 'See',
      'home_km_airport': 'km airp.',
      'home_guests_abbr': 'guests',
      'home_free_cancel': '✓ Free cancellation',
      'home_breakfast_incl': '🍳 Breakfast incl.',
      'home_wifi_free': '📶 Free WiFi',
      'home_hotel_fallback_desc': 'A well-located accommodation for your next getaway.',
      // Destinos page
      'destinos_title': 'Destinations',
      'destinos_hero_title': 'Explore destinations',
      'destinos_hero_subtitle': 'Discover the best places in the world',
      'destinos_search_hint': 'Search city or country…',
      'destinos_count_s': 'destination available',
      'destinos_count_p': 'destinations available',
      'destinos_empty': 'No destinations found',
      'destinos_error_load': 'Error loading destinations. Please try again.',
      'destinos_error_server': 'Unexpected server response.',
      'destinos_error_connection': 'Could not connect to the server. Check your connection.',
      'destinos_see_hotels': 'See hotels',
      'destinos_hotel_s': 'hotel',
      'destinos_hotel_p': 'hotels',
      'destinos_unknown_city': 'Unknown city',
      'destinos_unknown_country': 'Unknown country',
      // Mis Reservas page
      'reservas_refresh': 'Refresh',
      'reservas_tab_active': 'Active',
      'reservas_tab_history': 'History',
      'reservas_tab_cancelled': 'Cancelled',
      'reservas_total_invested': 'Total invested in trips',
      'reservas_label': 'bookings',
      'reservas_error_load': 'Error loading bookings. Please try again.',
      'reservas_cancel_title': 'Cancel booking',
      'reservas_cancel_confirm': 'Are you sure you want to cancel this booking? This action cannot be undone.',
      'reservas_keep': 'Keep',
      'reservas_cancelled_ok': 'Booking cancelled successfully',
      'reservas_cancel_error': 'Could not cancel the booking.',
      'reservas_cancel_conn_error': 'Connection error when cancelling the booking.',
      'reservas_confirmed': 'Booking confirmed',
      'reservas_completed': 'Stay completed',
      'reservas_today': 'Today!',
      'reservas_in_days_s': 'In {n} day',
      'reservas_in_days_p': 'In {n} days',
      'reservas_empty_active': 'No active bookings',
      'reservas_empty_active_sub': 'Book a hotel and it will appear here.',
      'reservas_empty_history': 'No booking history',
      'reservas_empty_history_sub': 'Past bookings will appear here.',
      'reservas_empty_cancelled': 'No cancelled bookings',
      'reservas_empty_cancelled_sub': 'You have not cancelled any bookings.',
      'reservas_checkin': 'Check-in',
      'reservas_checkout': 'Check-out',
      'reservas_duration': 'Duration',
      'reservas_night_s': 'night',
      'reservas_night_p': 'nights',
      'reservas_person_s': 'person',
      'reservas_person_p': 'people',
      'reservas_total_price': 'total price',
      'reservas_btn_cancel': 'Cancel',
      // Favoritos page
      'fav_title': 'My Favorites',
      'fav_empty_title': 'No favorites yet',
      'fav_empty_sub': 'Save your favorite hotels to find them easily later.',
      'fav_search_hotels': 'Search hotels',
      'fav_error_load': 'Error loading favorites. Please try again.',
      'fav_see': 'View',
      // Profile page
      'profile_title': 'My Profile',
      'profile_edit_tooltip': 'Edit profile',
      'profile_admin': 'Administrator',
      'profile_traveler': 'Traveler',
      'profile_stat_bookings': 'Bookings',
      'profile_stat_favorites': 'Favorites',
      'profile_stat_reviews': 'Reviews',
      'profile_section_personal': 'Personal information',
      'profile_section_extra': 'Additional data',
      'profile_section_account': 'Account',
      'profile_username': 'Username',
      'profile_email': 'Email',
      'profile_address': 'Address',
      'profile_birth_country': 'Country of birth',
      'profile_birth_date': 'Date of birth',
      'profile_required': 'Required field',
      'profile_email_invalid': 'Invalid email',
      'profile_date_format': 'Format: YYYY-MM-DD',
      'profile_year_invalid': 'Invalid year',
      'profile_month_invalid': 'Invalid month',
      'profile_day_invalid': 'Invalid day',
      'profile_save': 'Save changes',
      'profile_change_password': 'Change password',
      'profile_2fa': 'Two-step authentication',
      'profile_logout': 'Sign out',
      'profile_updated_ok': 'Profile updated successfully',
      'profile_updated_error': 'Error updating profile',
      'profile_connection_error': 'Connection error',
      // Footer
      'footer_description': 'Compare accommodations, filter with\nprecision and book without hassle.',
      'footer_terms': 'Terms',
      'footer_support': 'Customer support',
      'footer_destinations': 'Destinations',
      'footer_accommodations': 'Accommodations',
      'footer_bookings': 'My Bookings',
      'footer_favorites': 'Favorites',
      'footer_reviews': 'Reviews',
      // Search sentinels
      'home_all_cities': 'All',
      'home_all_countries': 'All',
      // About us page
      'about_title': 'About Us',
      'about_hero_title': 'About us',
      'about_hero_subtitle': 'Learn about our history and mission',
      'about_stat_hotels': 'Hotels',
      'about_stat_countries': 'Countries',
      'about_stat_rating': 'Rating',
      'about_stat_support': 'Support',
      'about_section_history': 'Our story',
      'about_history_card_title': 'From classroom to real project',
      'about_history_p1': 'Born in a Multiplatform Application Development (DAM) classroom, SkyTrip started as a small project among students passionate about technology and exploration. What began with lines of code and lots of coffee has become a vision to transform the way people discover their next destination.',
      'about_history_p2': 'From our first prototypes to the platform you see today, every line of code has been written with one idea in mind: making travel accessible, simple and exciting for everyone.',
      'about_section_mission': 'Our mission',
      'about_mission_quote': 'At SkyTrip we believe that traveling is not just about moving from point A to point B, but the experience that happens in between.',
      'about_mission_body': 'We are dedicated to simplifying the complexity of planning trips, offering an intuitive platform where inspiration meets ease of use. From the cobblestone streets of Rome to the skyscrapers of Tokyo, our database grows every day to bring you the best options at the best price.',
      'about_section_values': 'Our values',
      'about_value1_title': 'Trust',
      'about_value1_body': 'Transparent prices with no hidden charges on every booking.',
      'about_value2_title': 'Innovation',
      'about_value2_body': 'We continuously improve the experience with cutting-edge technology.',
      'about_value3_title': 'Accessibility',
      'about_value3_body': 'Travel is for everyone. We work to remove barriers.',
      'about_value4_title': 'Sustainability',
      'about_value4_body': 'We promote responsible tourism for the planet.',
      'about_section_team': 'The team',
      'about_section_tech': 'Technology',
      'about_tech_title': 'Built with modern technology',
      'about_cta_title': 'Ready to take off?',
      'about_cta_subtitle': 'Discover thousands of hotels in over 50 countries. Your next adventure starts here.',
      'about_cta_button': 'Explore hotels',
      // Condiciones page
      'terms_title': 'Terms and Conditions',
      'terms_page_title': 'SkyTrip Terms and Conditions',
      'terms_contact_title': 'Contact',
      'terms_contact_body': 'For any questions about these terms, you can contact us through our Customer Support page.',
      // Login extra
      'login_error_empty': 'Please enter your username and password.',
      // Trip detail page
      'trip_score_label': 'Overall score',
      'trip_per_night': 'per night',
      'trip_per_night_short': '/night',
      'trip_nights': 'nights',
      'trip_total': 'total',
      'trip_about': 'About this accommodation',
      'trip_description_original_lang': 'Description in original language (Spanish)',
      'trip_services': 'Services & facilities',
      'trip_location': 'Location',
      'trip_city_center': 'City center',
      'trip_nearest_airport': 'Nearest airport',
      'trip_available_rooms': 'Available rooms',
      'trip_searching_for': 'Searching for',
      'trip_no_rooms_title': 'No rooms available',
      'trip_no_rooms_sub': 'No rooms registered for this hotel.',
      'trip_guest_reviews': 'Guest reviews',
      'trip_no_reviews_title': 'No reviews yet',
      'trip_no_reviews_sub': 'Be the first to review this hotel.',
      'trip_house_rules': 'House rules',
      'trip_checkin_from': 'From 15:00',
      'trip_checkout_before': 'Before 12:00',
      'trip_smoking_no': 'Not allowed',
      'trip_pets_consult': 'Check with hotel',
      'trip_parties_no': 'Not allowed',
      'trip_free_cancel_24h': 'Free up to 24h before',
      'trip_policy_smoking': 'Smoking',
      'trip_policy_parties': 'Parties',
      'trip_policy_cancellation': 'Cancellation',
      'trip_review_today': 'Today',
      'trip_review_yesterday': 'Yesterday',
      'trip_days_ago_pre': '',
      'trip_days_ago_suf': 'days ago',
      'trip_share_tooltip': 'Share',
      'trip_share_copied': 'Link copied',
      'trip_edit_tooltip': 'Edit hotel',
      'trip_settings_tooltip': 'Settings',
      'trip_login_title': 'Sign in',
      'trip_login_to_book': 'You need an account to book. Would you like to sign in?',
      'trip_room_default': 'Room',
      'trip_room_recommended': 'RECOMMENDED',
      'trip_room_insuf_cap': 'INSUFFICIENT CAPACITY',
      'trip_room_wifi': 'Free WiFi',
      'trip_room_breakfast': 'Breakfast',
      'trip_room_ac': 'A/C',
      'trip_room_jacuzzi': 'Jacuzzi',
      'trip_room_book': 'Book now',
      'trip_room_unavailable': 'Unavailable',
      'trip_no_hotel_id': 'Could not identify the hotel.',
      'trip_error_rooms': 'Error loading rooms',
      'trip_error_server': 'Could not connect to server.',
      'trip_rating_exceptional': 'Exceptional',
      'trip_rating_fantastic': 'Fantastic',
      'trip_rating_very_good': 'Very good',
      'trip_rating_good': 'Good',
      'trip_rating_fair': 'Fair',
      'trip_rating_correct': 'Correct',
      'trip_up_to': 'Up to',
      'trip_guests': 'guests',
      'trip_km_center': 'km from center',
      'trip_km_airport': 'km airport',
      'trip_stars_label': 'stars',
      'trip_no_category': 'No category',
      'trip_you_need': 'you need',
      'room_person_s': 'person',
      'room_person_p': 'people',
      'guest_adult_s': 'adult',
      'guest_adult_p': 'adults',
      'guest_child_s': 'child',
      'guest_child_p': 'children',
      // Hotel card (home)
      'card_free_cancel': '✓ Free cancel',
      'card_breakfast_incl': '🍳 Breakfast incl.',
      'card_wifi_free': '📶 Free WiFi',
      // Carousels
      'carousel_fivestar_title': '5-Star Hotels',
      'carousel_fivestar_subtitle': 'Guaranteed luxury and excellence',
      'carousel_centric_title': 'Central Hotels',
      'carousel_centric_subtitle': 'In the heart of the city',
      'carousel_bestvalue_title': 'Best Value',
      'carousel_bestvalue_subtitle': 'High rating, fair price',
      // Confirmar reserva page
      'booking_title': 'Complete Booking',
      'booking_room_label': 'Room',
      'booking_full_name': 'Full name',
      'booking_dni': 'ID / Passport',
      'booking_phone': 'Phone',
      'booking_name_required': 'Please enter your name',
      'booking_name_letters_only': 'Letters and spaces only',
      'booking_dni_required': 'Please enter your ID number',
      'booking_dni_invalid': 'Invalid ID: 8 digits and one letter',
      'booking_phone_required': 'Please enter your phone number',
      'booking_phone_invalid': 'Invalid phone: 9 digits required',
      'booking_dates_title': 'Travel Dates',
      'booking_dates_placeholder': 'Select your dates here',
      'booking_change_dates': 'Change Dates',
      'booking_accept_dates': 'Accept Dates',
      'booking_dates_accepted': 'Dates accepted',
      'booking_cancel_dates': 'Remove Dates',
      'booking_go_back': 'Go Back',
      'booking_price_summary': 'Price Summary',
      'booking_price_night': 'Price per night',
      'booking_num_nights': 'Number of nights',
      'booking_total': 'Total',
      'booking_guests_title': 'Selected guests',
      'booking_need_crib': 'Crib needed',
      'booking_include_breakfast': 'Include breakfast',
      'booking_fix_errors': 'Please fix the form errors.',
      'booking_select_dates': 'Please select your travel dates.',
      'booking_confirmed': 'Booking confirmed successfully',
      'booking_error': 'Error confirming the booking',
      'booking_confirm_btn': 'CONFIRM BOOKING',
      'booking_adult_label': 'Adult',
      'booking_child_label': 'Child',
      'booking_years': 'years',
      'booking_nights': 'nights',
    },
  };
}
